sudo: false
language: elixir
elixir:
  - 1.0.2
services:
  - elasticsearch
script: "mix test"
notifications:
  email: false
  slack:
    rooms:
      - zatvobor:eLjCTZD2l85xl19hsSdxkMdN##oss-feed
    on_success: change
